services:
  web:
    build: .
    ports:
      - "80:3000"
    command: npm start
    x-develop:
      watch:
        - path: ./src
          target: /app/src/
          ignore:
            - ./src/node_modules
          action: rebuild
