name: Playwright Tests
on:
  push:
    branches: api-testing-playwright
env:
  ROOT_PATH: '${{github.workspace}}'
  
jobs:
  Testing:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:

    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Installing NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Installing dependencies
      run: npm install
      working-directory: '${{env.ROOT_PATH}}'

    - name: Installing Playwright Browsers
      run: yarn playwright install --with-deps
      working-directory: '${{env.ROOT_PATH}}'

    - name: Starting Server
      run: npm start
      working-directory: '${{env.ROOT_PATH}}'

    - name: Running tests
      run: npm test
      working-directory: '${{env.ROOT_PATH}}'
