name: Playwright Tests
on:
  push:
    branches: api-testing-playwright
env:
  ROOT_PATH: '${{github.workspace}}'
  REPORT_NAME: '${{github.run_id}}.html'
  
jobs:
  Testing:
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:

    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Installing NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Configuring AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/github-actions-access
        aws-region: us-east-2
        
    - name: Installing AWS CLI
      run: sudo apt update && sudo apt install -y awscli

    - name: Installing dependencies
      run: npm install
      working-directory: '${{env.ROOT_PATH}}'

    - name: Installing Playwright Browsers
      run: yarn playwright install --with-deps
      working-directory: '${{env.ROOT_PATH}}'

    - name: Starting Server
      run: npm start
      working-directory: '${{env.ROOT_PATH}}'

    - name: Running tests
      run: npm test
      working-directory: '${{env.ROOT_PATH}}'
    
    - name: Uploading test reports to Amazon S3
      if: always()
      run: |
       aws s3 cp "${{env.ROOT_PATH}}/playwright-report/index.html" s3://helloworld-api-test-reports/playwright-report/'${{env.REPORT_NAME}}'

    - name: Public URL of Report
      run: echo "https://helloworld-api-test-reports.s3.us-east-2.amazonaws.com/playwright-report/${{env.REPORT_NAME}}"
