name: Playwright Tests
on:
  push:
    branches: api-testing-playwright

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:

    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Installing NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Installing dependencies
      run: npm install

    - name: Installing Playwright Browsers
      run: npx playwright install

    - name: Starting Server
      run: npm start

    - name: Running tests
      run: npm test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10
